DROP TABLE IF EXISTS dbo.Arrangements
DROP TABLE IF EXISTS dbo.Cities

DROP TABLE IF EXISTS dbo.AspNetRoleClaims
DROP TABLE IF EXISTS dbo.AspNetUserClaims
DROP TABLE IF EXISTS dbo.AspNetUserLogins
DROP TABLE IF EXISTS dbo.AspNetUserRoles
DROP TABLE IF EXISTS dbo.AspNetUserTokens
DROP TABLE IF EXISTS dbo.AspNetRoles
DROP TABLE IF EXISTS dbo.AspNetUsers
DROP TABLE IF EXISTS dbo.__EFMigrationsHistory
